# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 主题 REDEFINE 配置文件 V2
# 作者：EVANNOTFOUND
# GitHub: https://github.com/EvanNotFound/hexo-theme-redefine
# 文档: https://redefine-docs.ohevan.com
# 演示: https://redefine.ohevan.com
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 基本信息 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/info
info:
  # 网站标题
  title: Kwang's Blog
  # 网站副标题
  subtitle: Everyone is born unique.
  # 作者名称
  author: Wkr
  # 网站 URL
  url: https://blog.wkr-dev.top
# 基本信息 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 图片配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/defaults
defaults:
  # 网站图标
  favicon: /images/redefine-favicon.svg
  # 网站 logo
  logo: 
  # 网站头像
  avatar: https://cdn.wkr-dev.top/file/blog/img/oaBRczOi.webp
# 图片配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 颜色 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/colors
colors:
  # 主色调
  primary: "#A31F34"
  # 辅助色
  secondary:
  # 默认主题模式初始值（将被 prefers-color-scheme 覆盖）
  default_mode: light # light, dark
# 颜色 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 网站定制化 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/global
global:
  # 自定义全局字体
  fonts:
    # 中文字体
    chinese: 
      enable: true # 是否启用自定义中文字体
      family: Noto Sans SC # 字体家族
      url: https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap # 字体 CSS 文件 URL
    # 英文字体
    english: 
      enable: false # 是否启用自定义英文字体
      family:  # 字体家族
      url:  # 字体 CSS 文件 URL
    # 自定义标题字体（导航栏、侧边栏）
    title:
      enable: false # 是否启用自定义标题字体
      family:  # 字体家族
      url:  # 字体 CSS 文件 URL
  # 内容最大宽度
  content_max_width: 1000px
  # 侧边栏宽度
  sidebar_width: 210px
  # 鼠标悬停效果
  hover:
    shadow: true # 阴影效果
    scale: false # 缩放效果
  # 滚动进度
  scroll_progress:
    bar: false # 进度条
    percentage: true # 百分比
  # 网站计数器
  website_counter:
    url: https://cn.vercount.one/js # 计数器 API URL（无需更改）
    enable: true # 是否启用网站计数器
    site_pv: true # 站点页面浏览量
    site_uv: true # 站点独立访客数
    post_pv: true # 文章页面浏览量
  # 是否启用单页体验（使用 swup）。参见 https://swup.js.org/。类似于 pjax
  single_page: true
  # 是否启用预加载器。
  preloader:
    enable: false
    custom_message: # 自定义消息。如果为空，将显示网站标题
  # 侧边工具设置
  side_tools:
    # 是否启用设置按钮的齿轮旋转动画
    gear_rotation: true
    # 是否在页面加载时自动展开工具列表
    auto_expand: true
  # 是否启用开放图谱协议
  open_graph:
    enable: true
    image: /images/redefine-og.webp  # 默认的 og:image
    description: Everyone is born unique.
  # Google Analytics
  google_analytics:
    enable: false # 是否启用 Google Analytics
    id:  # Google Analytics 衡量 ID
# 网站定制化 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束
    

# FONTAWESOME >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/basic/fontawesome
fontawesome: # Pro v6.2.1
  # 纤细版本
  thin: false
  # 轻盈版本
  light: false
  # 双色调版本
  duotone: false
  # Sharp Solid 版本
  sharp_solid: true
# FONTAWESOME <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 首页横幅 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/home/home_banner
home_banner:
  # 是否启用首页横幅
  enable: true
  # 首页横幅样式
  style: fixed # static 或 fixed
  # 首页横幅图片
  image: 
    light: /images/wallhaven-wqery6-light.webp # 浅色模式
    dark: /images/wallhaven-wqery6-dark.webp # 深色模式
  # 首页横幅标题
  title: Everyone is born unique.
  # 首页横幅副标题
  subtitle:
    text: [] # 副标题文本，数组
    hitokoto:  # 一言配置
      enable: true # 是否启用一言
      show_author: false # 是否显示作者
      api: https://v1.hitokoto.cn # API URL，可以添加类型，参见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    typing_speed: 100 # 打字速度（毫秒）
    backing_speed: 80 # 删除速度（毫秒）
    starting_delay: 500 # 开始延迟（毫秒）
    backing_delay: 1500 # 删除延迟（毫秒）
    loop: true # 是否循环
    smart_backspace: true # 是否智能退格
  # 首页横幅文本颜色
  text_color: 
    light: "#fff" # 浅色模式
    dark: "#d1d1b6" # 深色模式
  # 文本的具体样式
  text_style: 
    # 标题字体大小
    title_size: 2.8rem
    # 副标题字体大小
    subtitle_size: 1.5rem
    # 标题与副标题之间的行高
    line_height: 1.2
  # 首页横幅自定义字体
  custom_font: 
    # 是否启用自定义字体
    enable: false
    # 字体家族
    family: 
    # 字体 CSS 文件 URL
    url:
  # 首页横幅社交链接
  social_links:
    # 是否启用
    enable: true
    # 社交链接样式
    style: default # default, reverse, center
    # 社交链接
    links:
      - icon: github # 也可以是 "fa-brands fa-github"
        url: https://github.com/wkk-dev
      - icon: email
        url: wkk-dev@qq.com
      - icon: /images/custom-icon.svg
        url:
    # 带有二维码抽屉的社交链接
    qrs:
      - icon: weixin
        qr:
      - icon: /images/custom-icon.svg
        qr:
# 首页横幅 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 导航栏 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/home/navbar
navbar:
  # 自动隐藏导航栏
  auto_hide: false
  # 导航栏背景颜色
  color:
    left: "#f78736" # 左侧
    right: "#367df7"  # 右侧
    transparency: 35 # 透明度百分比 (10-99)
  # 导航栏宽度（通常无需修改）
  width:
    home: 1200px # 首页
    pages: 1000px # 其他页面
  # 导航栏链接
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house # 可以为空
    # Archives: 
    #   path: /archives 
    #   icon: fa-regular fa-archive # 可以为空
    # Status: 
    #   path: https://status.ohevan.com/
    #   icon: fa-regular fa-chart-bar
     About: 
       icon: fa-regular fa-user
       submenus:
         Me: /about
         Github: https://github.com/EvanNotFound/hexo-theme-redefine
    #     Blog: https://ohevan.com
    #     Friends: /friends
    # Links: 
    #   icon: fa-regular fa-link
    #   submenus:
    #     Link1: /link1
    #     Link2: /link2
    #     Link3: /link3
    # ...... # 你可以添加更多
  # 导航栏搜索（本地搜索）。需要 hexo-generator-searchdb (npm i hexo-generator-searchdb)。参见 https://github.com/theme-next/hexo-generator-searchdb
  search:
    # 是否启用
    enable: true
    # 页面加载时预加载搜索数据
    preload: true
# 导航栏 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 首页文章设置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/home/home
home:
  # 侧边栏设置
  sidebar:
    enable: false # 是否启用侧边栏
    position: left # 侧边栏位置。left, right
    first_item: menu # 侧边栏中的第一个项目。menu, info
    announcement: # 公告文本
    show_on_mobile: true # 是否在移动设备菜单中显示侧边栏导航
    links:
       Archives: 
         path: /archives 
         icon: fa-regular fa-archive # 可以为空
       Tags: 
         path: /tags 
         icon: fa-regular fa-tags # 可以为空
       Categories: 
         path: /categories 
         icon: fa-regular fa-folder # 可以为空
      # ...... # 你可以添加更多
  # 文章日期格式
  article_date_format: auto # auto, relative, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss 等。
  # 文章摘要长度
  excerpt_length: 200 # 文章摘要的最大长度
  # 文章分类可见性
  categories:
    enable: true  # 是否启用
    limit: 3 # 最大显示分类数
  # 文章标签可见性
  tags:
    enable: true  # 是否启用
    limit: 3  # 最大显示标签数
# 首页文章设置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 文章 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/posts/articles
articles:
  # 设置文章样式
  style:
    font_size: 16px # 字体大小
    line_height: 1.5 # 行高
    image_border_radius: 14px # 图片边框半径
    image_alignment: center # 图片对齐方式。left, center
    image_caption: false # 是否显示图片说明
    link_icon: true # 是否显示链接图标
    delete_mask: true # 为 <del> 标签添加蒙版效果，默认隐藏内容，悬停时显示
    title_alignment: left # 标题对齐方式。left, center
    headings_top_spacing: # h1-h6 标题的上边距
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  # 字数统计。需要 hexo-wordcount (npm install hexo-wordcount)。参见 https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # 是否启用
    count: true # 是否显示字数
    min2read: true # 是否显示阅读时间
  # 作者标签
  author_label: 
    enable: true # 是否启用
    auto: true # 是否自动添加作者标签，例如 Lv1, Lv2, Lv3...
    list: []
  # 代码块设置
  code_block:
    copy: true # 是否启用代码块复制按钮
    style: mac # mac | simple
    highlight_theme: # highlightjs 代码高亮的配色方案。预览请见 https://highlightjs.org/examples
      light: github # 浅色模式主题，支持：github, atom-one-light, default
      dark: vs2015 # 深色模式主题，支持：github-dark, monokai-sublime, vs2015, night-owl, atom-one-dark, nord, tokyo-night-dark, a11y-dark, agate
    font: # 自定义字体
      enable: false # 是否启用
      family: # 字体家族
      url: # 字体 CSS 文件 URL
  # 目录设置
  toc:
    enable: true # 是否启用 TOC
    max_depth: 5 # TOC 深度
    number: true # 是否自动给 TOC 添加编号
    expand: true # 是否展开 TOC
    init_open: true # 默认打开目录
  # 是否启用版权声明
  copyright:
    enable: true # 是否启用
    default: cc_by_nc_sa # 默认许可证，可选：cc_by_nc_sa, cc_by_nd, cc_by_nc, cc_by_sa, cc_by, all_rights_reserved, public_domain
  # 是否启用图片懒加载
  lazyload: true
  # Pangu.js（自动在中英文之间添加空格）。参见 https://github.com/vinta/pangu.js
  pangu_js: false
  # 文章推荐。需要 nodejieba (npm install nodejieba)。移植自 hexo-theme-volantis。
  recommendation:
    # 是否启用文章推荐
    enable: false
    # 文章推荐标题
    title: 推荐阅读
    # 最大显示文章数
    limit: 3
    # 移动端最大显示文章数
    mobile_limit: 2
    # 占位图片
    placeholder: /images/wallhaven-wqery6-light.webp
    # 跳过目录
    skip_dirs: []
# 文章 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 评论 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/posts/comment
comment:
  # 是否启用评论
  enable: true
  # 评论系统
  system: twikoo # waline, gitalk, twikoo, giscus, utterances, artalk
  # 系统配置
  config:
    # Waline 评论系统。参见 https://waline.js.org/
    waline:
      serverUrl: https://example.example.com # Waline 服务器 URL，例如 https://example.example.com
      lang: zh-CN # Waline 语言，例如 zh-CN, en-US。参见 https://waline.js.org/guide/client/i18n.html
      emoji: [] # Waline 表情，参见 https://waline.js.org/guide/features/emoji.html
      recaptchaV3Key: # Google reCAPTCHA v3 密钥。参见 https://waline.js.org/reference/client/props.html#recaptchav3key
      turnstileKey: # Turnstile 密钥。参见 https://waline.js.org/reference/client/props.html#turnstilekey
      reaction: false # Waline 反应。参见 https://waline.js.org/reference/client/props.html#reaction
    # Gitalk 评论系统。参见 https://github.com/gitalk/gitalk
    gitalk:
      clientID: # GitHub 应用程序客户端 ID
      clientSecret: # GitHub 应用程序客户端密钥
      repo: # GitHub 仓库
      owner: # GitHub 仓库所有者
      proxy: # GitHub 仓库代理
    # Twikoo 评论系统。参见 https://twikoo.js.org/
    twikoo:
      version: 1.6.44 # Twikoo 版本，如果不了解请不要修改
      server_url: https://twikoo.api.wkr-dev.top/.netlify/functions/twikoo # Twikoo 服务器 URL，例如 https://example.example.com
      region: # Twikoo 区域，可以为空
    # Giscus 评论系统。参见 https://giscus.app/
    giscus:
      repo: # Github 仓库名称，例如 EvanNotFound/hexo-theme-redefine
      repo_id: # Github 仓库 ID
      category: # Github 讨论分类
      category_id: # Github 讨论分类 ID
      mapping: pathname # 用作页面唯一标识的值，例如 pathname, url, title, og:title。如果启用了 PJAX，请勿使用 og:title，因为页面更改时 og:title 不会更新
      strict: 0 # 是否启用严格模式，例如 0, 1
      reactions_enabled: 1 # 是否启用反应，例如 0, 1
      emit_metadata: 0 # 是否发送元数据，例如 0, 1
      lang: en # Giscus 语言，例如 en, zh-CN, zh-TW
      input_position: bottom # 将评论框放在评论的上方/下方，例如 top, bottom
      loading: lazy # 懒加载评论
    # Artalk 评论系统。参见 https://artalk.js.org/
    artalk:
      server: # Artalk 服务器 URL，例如 https://artalk.example.com
      site: # Artalk 管理后台显示的站点名称（应与服务端站点配置一致）
    # Utterances 评论系统。参见 https://utteranc.es/
    utterances:
      repo: # GitHub 仓库名称，例如 owner/repo（必须启用 Issues）
      issue_term: pathname # pathname, url, title, og:title（单页模式推荐使用 pathname）
      issue_number: # 使用特定的 Issue 编号替代 issue_term
      label: # 为创建的 Issues 添加的可选标签
      theme_light: github-light # 浅色主题
      theme_dark: github-dark # 深色主题
# 评论 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 页脚 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/footer
footer:
  # 显示网站运行时间
  runtime: true # 是否显示网站运行时间
  # 页脚图标，在此处填写 fontawesome 图标代码
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  # 网站开始时间，格式：YYYY/MM/DD HH:mm:ss
  start: 2024/11/15 11:00:00
  # 站点统计
  statistics: true # 是否显示站点统计（总文章数、总字数）
  # 页脚自定义信息
  customize:
  # ICP 备案号。参见 https://beian.miit.gov.cn/
  icp:
    enable: true # 是否启用
    number: 萌ICP备20260203号 # ICP 备案号
    url: https://icp.gov.moe/?keyword=20260203 # ICP 备案链接
# 页脚 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 注入 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/inject
inject:
  # 是否启用注入
  enable: true
  # 注入自定义 head HTML 代码
  head: 
    -
    -
  # 注入自定义 footer HTML 代码
  footer:
    - <div style="https://cdn.wkr-dev.top/file/blog/css/eLurUTpo.css"></div>
    -  
# 注入 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 插件 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/plugins
plugins:
  # RSS 订阅。需要 hexo-generator-feed (npm i hexo-generator-feed)。参见 https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: true # 是否启用
  # Aplayer。参见 https://github.com/DIYgod/APlayer
  aplayer:
    enable: false # 是否启用
    type: fixed # fixed, mini
    audios:
      - name: # 音频名称
        artist: # 音频艺术家
        url: # 音频 URL
        cover: # 音频封面 URL
        lrc: # 音频歌词
#      - name: # 音频名称
#        artist: # 音频艺术家
#        url: # 音频 URL
#        cover: # 音频封面 URL
#        lrc: # 音频歌词
      # .... 你可以在此添加更多音频
  # Mermaid JS。需要 hexo-filter-mermaid-diagrams (npm i hexo-filter-mermaid-diagrams)。参见 https://mermaid.js.org/
  mermaid:
    enable: true # 是否启用 mermaid
    version: "11.4.1" # 默认 v11.4.1
    theme:
      light: "default"
      dark: "dark"
# 插件 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# 页面模板 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/page_templates
page_templates:
  # 友链页面列数
  friends_column: 2
  # 标签页面样式
  tags_style: blur # blur, cloud
  # 瀑布流页面批次大小
  masonry:
    batch_size: 12
    initial_batch_size: 24
# 页面模板 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束


# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/cdn
cdn:
  # 是否启用 CDN
  enable: false
  # CDN 提供商
  provider: npmmirror # npmmirror, zstatic, cdnjs, jsdelivr, unpkg, custom
  # 自定义 CDN URL
  # 格式示例：https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
  # ${path} 必须指向主题 "source" 文件夹的根目录
  custom_url: 
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 结束

# 开发者模式 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 开始
# 文档: https://redefine-docs.ohevan.com/developer
developer:
  # 是否启用开发者模式（仅适用于想要修改主题源代码的开发者，不适用于普通用户）
  enable: false
# 开发者模式 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< END